### ISSUE TITLE
Iteration 2 Analysis report missing sections

### ISSUE THREAD

**Issue by ugurdogrusoz** [Seftali/1.A-Medieval-Tower-Defense#7]
See project description document for sections specifically for iteration 2. You're missing those.

**Comment by bugraaydin** [comment]
We actually embedded our additional requirements on our play game requirement, sorry about that. I updated those additional requirements on a new specific section and uploaded the new document.

**Comment by bugraaydin** [comment]
Should I delete the old analysis document?

**Comment by ugurdogrusoz** [comment]
@bugraaydin No, keep the old document please.
